package com.shouyu.syrums.domain.entity;

import com.shouyu.dframework.entity.Entity;

public class UcAccount extends Entity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uc_account.id
     *
     * @mbg.generated Sun Nov 21 14:02:01 CST 2021
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uc_account.login_name
     *
     * @mbg.generated Sun Nov 21 14:02:01 CST 2021
     */
    private String loginName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uc_account.pwd
     *
     * @mbg.generated Sun Nov 21 14:02:01 CST 2021
     */
    private String pwd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uc_account.user_id
     *
     * @mbg.generated Sun Nov 21 14:02:01 CST 2021
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uc_account.create_time
     *
     * @mbg.generated Sun Nov 21 14:02:01 CST 2021
     */
    private Long createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uc_account.create_user
     *
     * @mbg.generated Sun Nov 21 14:02:01 CST 2021
     */
    private String createUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uc_account.is_delete
     *
     * @mbg.generated Sun Nov 21 14:02:01 CST 2021
     */
    private Short isDelete;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uc_account.id
     *
     * @return the value of uc_account.id
     *
     * @mbg.generated Sun Nov 21 14:02:01 CST 2021
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uc_account.id
     *
     * @param id the value for uc_account.id
     *
     * @mbg.generated Sun Nov 21 14:02:01 CST 2021
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uc_account.login_name
     *
     * @return the value of uc_account.login_name
     *
     * @mbg.generated Sun Nov 21 14:02:01 CST 2021
     */
    public String getLoginName() {
        return loginName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uc_account.login_name
     *
     * @param loginName the value for uc_account.login_name
     *
     * @mbg.generated Sun Nov 21 14:02:01 CST 2021
     */
    public void setLoginName(String loginName) {
        this.loginName = loginName == null ? null : loginName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uc_account.pwd
     *
     * @return the value of uc_account.pwd
     *
     * @mbg.generated Sun Nov 21 14:02:01 CST 2021
     */
    public String getPwd() {
        return pwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uc_account.pwd
     *
     * @param pwd the value for uc_account.pwd
     *
     * @mbg.generated Sun Nov 21 14:02:01 CST 2021
     */
    public void setPwd(String pwd) {
        this.pwd = pwd == null ? null : pwd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uc_account.user_id
     *
     * @return the value of uc_account.user_id
     *
     * @mbg.generated Sun Nov 21 14:02:01 CST 2021
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uc_account.user_id
     *
     * @param userId the value for uc_account.user_id
     *
     * @mbg.generated Sun Nov 21 14:02:01 CST 2021
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uc_account.create_time
     *
     * @return the value of uc_account.create_time
     *
     * @mbg.generated Sun Nov 21 14:02:01 CST 2021
     */
    public Long getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uc_account.create_time
     *
     * @param createTime the value for uc_account.create_time
     *
     * @mbg.generated Sun Nov 21 14:02:01 CST 2021
     */
    public void setCreateTime(Long createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uc_account.create_user
     *
     * @return the value of uc_account.create_user
     *
     * @mbg.generated Sun Nov 21 14:02:01 CST 2021
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uc_account.create_user
     *
     * @param createUser the value for uc_account.create_user
     *
     * @mbg.generated Sun Nov 21 14:02:01 CST 2021
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser == null ? null : createUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uc_account.is_delete
     *
     * @return the value of uc_account.is_delete
     *
     * @mbg.generated Sun Nov 21 14:02:01 CST 2021
     */
    public Short getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uc_account.is_delete
     *
     * @param isDelete the value for uc_account.is_delete
     *
     * @mbg.generated Sun Nov 21 14:02:01 CST 2021
     */
    public void setIsDelete(Short isDelete) {
        this.isDelete = isDelete;
    }
}